//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSR_Gadget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSR_Gadget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 [None]
        ///1002900 Depths (Entrance)
        ///1002950 Depths (Gaping Dragon&apos;s Room)
        ///1002960 Depths (Bonfire)
        ///1012960 Undead Burg (Pre-Dragon Scare)
        ///1012961 Undead Parish (Sunlight Altar Bonfire)
        ///1012962 Undead Burg (Bonfire)
        ///1012964 Undead Parish (Bonfire)
        ///1012965 Undead Parish (Near Boar)
        ///1012966 Undead Parish (Near Cell)
        ///1020980 Firelink Shrine (Bonfire, repeat)
        ///1022960 Firelink Shrine (Bonfire)
        ///1102511 Painted World of Ariamis (Rope Bridge)
        ///1102960 Painted World of Ariamis (Bonfire)
        ///1102961 Painted World of Ariami [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bonfires {
            get {
                return ResourceManager.GetString("Bonfires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:  48 b9 fe fe fe fe fe    movabs rcx,0xfefefefefefefefe
        ///7:  fe fe fe
        ///a:  48 8b 09                mov    rcx,QWORD PTR [rcx]
        ///d:  ba 01 00 00 00          mov    edx,0x1
        ///12: 48 83 ec 38             sub    rsp,0x38
        ///16: 49 be fe fe fe fe fe    movabs r14,0xfefefefefefefefe
        ///1d: fe fe fe
        ///20: 41 ff d6                call   r14
        ///23: 48 83 c4 38             add    rsp,0x38
        ///27: c3                      ret .
        /// </summary>
        internal static string BonfireWarp {
            get {
                return ResourceManager.GetString("BonfireWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 4 11 08 12 13 13 11 09 09 Warrior
        ///1 5 14 10 10 11 11 10 09 11 Knight
        ///2 3 10 11 10 10 14 12 11 08 Wanderer
        ///3 5 09 11 09 09 15 10 12 11 Thief
        ///4 4 12 08 14 14 09 11 08 10 Bandit
        ///5 4 11 09 11 12 14 11 09 09 Hunter
        ///6 3 08 15 08 09 11 08 15 08 Sorcerer
        ///7 1 10 12 11 12 09 12 10 08 Pyromancer
        ///8 2 11 11 09 12 08 11 08 14 Cleric
        ///9 6 11 11 11 11 11 11 11 11 Deprived.
        /// </summary>
        internal static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:  ba fe fe fe fe          mov    edx,0xfefefefe
        ///5:  41 b9 fe fe fe fe       mov    r9d,0xfefefefe
        ///b:  41 b8 fe fe fe fe       mov    r8d,0xfefefefe
        ///11: 41 bc fe fe fe fe       mov    r12d,0xfefefefe
        ///17: 48 a1 fe fe fe fe fe    movabs rax,ds:0xfefefefefefefefe
        ///1e: fe fe fe
        ///21: c6 44 24 38 01          mov    BYTE PTR [rsp+0x38],0x1
        ///26: 40 88 7c 24 30          mov    BYTE PTR [rsp+0x30],dil
        ///2b: c6 44 24 28 01          mov    BYTE PTR [rsp+0x28],0x1
        ///30: 4c 8b 78 10             mov    r15,QWORD PTR [rax+0x10]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItem {
            get {
                return ResourceManager.GetString("GetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:  48 ba 00 00 00 00 ff    movabs rdx,0xffffffff00000000
        ///7:  ff ff ff
        ///a:  48 b9 00 00 00 00 ff    movabs rcx,0xffffffff00000000
        ///11: ff ff ff
        ///14: 48 83 ec 38             sub    rsp,0x38
        ///18: 49 be 20 99 68 40 01    movabs r14,0x140689920
        ///1f: 00 00 00
        ///22: 41 ff d6                call   r14
        ///25: 48 83 c4 38             add    rsp,0x38
        ///29: c3                      ret .
        /// </summary>
        internal static string LevelUp {
            get {
                return ResourceManager.GetString("LevelUp", resourceCulture);
            }
        }
    }
}
